### ISSUE TITLE
problems running this

### ISSUE THREAD

**Issue by evanrich** [evilpete/RainEagle#5]
```
root@metrics:/home/erichardson/RainEagle# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import RainEagle
>>> raineagle = RainEagle.Eagle(debug=0, addr="192.168.1.222")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "RainEagle/EagleClass.py", line 192, in __init__
    mysetting = self.get_setting_data()
  File "RainEagle/EagleClass.py", line 533, in get_setting_data
    comm_responce = self._send_http_comm("get_setting_data", MacId=macid)
  File "RainEagle/EagleClass.py", line 813, in _send_http_comm
    req = urllib2.Request(url, commstr, headers={ "Authorization" : 'Basic ' + base64.b64encode(self.username+":"+self.password) })
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>>
```

cloned the repo, fired up python, stepped through...as soon as I got to the raineagle=... line, it errors out.

**Comment by evanrich** [comment]
fixed by adding username= and password=.   docs should be updated.
